version: '3.8'

services:
  salmonid-app:
    build: .
    ports:
      - "7860:7860"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - CUDA_VISIBLE_DEVICES=0
    volumes:
      - ./botsort_weights:/app/botsort_weights
    restart: unless-stopped 